"""
Firestore output strategy.

Writes each record as one document to a Firestore collection. Requires:

    1. The `firebase-admin` package: `pip install firebase-admin`
    2. A Firebase service-account JSON key file. Get one from:
       Firebase Console → Project settings → Service accounts → Generate new private key
    3. The path to that JSON file in the configuration (or via an
       environment variable like FIREBASE_SERVICE_ACCOUNT).

Each record's `to_dict()` is the document body. Document IDs are
auto-generated by Firestore so writes are append-only — re-running the
program produces new documents rather than overwriting old ones.
"""
from __future__ import annotations

import logging
from typing import Any

from ..interfaces import IOutputStrategy

logger = logging.getLogger(__name__)


class FirestoreOutputStrategy(IOutputStrategy):
    name = "firestore"

    def __init__(self, credentials_path: str, collection: str) -> None:
        self._credentials_path = credentials_path
        self._collection_name = collection
        self._client: Any = None
        self._collection: Any = None

    def open(self) -> None:
        try:
            import firebase_admin
            from firebase_admin import credentials, firestore
        except ImportError as e:
            raise RuntimeError(
                "firebase-admin is not installed. Run: pip install firebase-admin"
            ) from e

        # firebase_admin allows only one default app per process; reuse it
        # if it's already initialized (matters when tests or repeated calls
        # happen in the same Python interpreter).
        if not firebase_admin._apps:
            logger.info("Initializing Firebase Admin SDK with %s",
                        self._credentials_path)
            cred = credentials.Certificate(self._credentials_path)
            firebase_admin.initialize_app(cred)
        else:
            logger.info("Reusing existing Firebase Admin app")

        self._client = firestore.client()
        self._collection = self._client.collection(self._collection_name)
        logger.info("Ready to write to Firestore collection %r",
                    self._collection_name)

    def write(self, record) -> None:
        # Firestore generates the document ID for us — append-only audit log.
        self._collection.add(record.to_dict())

    def close(self) -> None:
        # firestore.Client uses gRPC channels under the hood; they're
        # cleaned up on process exit. No explicit close needed for the
        # subprocess-per-event use case.
        self._client = None
        self._collection = None
